server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: openai_chat_completions
          uri: https://api.openai.com
          predicates:
            - Path=/v1/chat/completions
          filters:
            # We preserve the host header so we don't accidentally send 'localhost' to OpenAI
            - PreserveHostHeader
            # Custom Inspection Filter (Inbound)
            - InspectionFilter
            # Custom Scanner Filter (Outbound)
            - OutboundScannerFilter
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
